# Stolen from http://jekyllrb.com/docs/continuous-integration/travis-ci/

language: ruby
rvm:
- 2.4.1

before_script:
 - chmod +x ./script/cibuild # I'm lazy

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false