# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog | Ethan Bulmer
email: ethan@ethanbulmer.com
author: Ethan Bulmer
description: >
  Ethan Bulmer's software engineering blog
baseurl: ""
url: "blog.ethanbulmer.com" # the base hostname & protocol for your site, e.g. http://example.com (Do I need to use this?)
permalink: /:title
github_username: PureGero

google_analytics: G-0395TMQMZ5

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

exclude: [vendor, README.md, Gemfile, Gemfile.lock, CNAME, script]